import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const sb=createClient("https://cnynfycmvmcjzaevhvmw.supabase.co","sb_publishable_9Du-_m5etaGt-vCBkDvROw_-0sdB_jT");
const $=s=>document.querySelector(s),safe=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const toast=t=>{const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)};
const state={tab:"products",brands:[],categories:[],products:[],promotions:[],groups:[],options:[],links:[],places:[],orders:[],calls:[]};
async function boot(){const {data:{session}}=await sb.auth.getSession();if(session)await enter();else showAuth()}
function showAuth(){$("#authView").classList.remove("hidden");$("#adminView").classList.add("hidden")}
async function enter(){const {data,error}=await sb.rpc("is_admin");if(error||!data){$("#authMessage").textContent="Este correo no está autorizado como administrador.";await sb.auth.signOut();showAuth();return}$("#authView").classList.add("hidden");$("#adminView").classList.remove("hidden");await loadAll();render()}
async function loadAll(){const [b,c,p,pr,g,o,l,pl,ord,calls]=await Promise.all([
 sb.from("brands").select("*").order("sort_order"),sb.from("categories").select("*").order("sort_order"),sb.from("products").select("*").order("sort_order"),
 sb.from("promotions").select("*").order("sort_order"),sb.from("option_groups").select("*").order("sort_order"),sb.from("options").select("*").order("sort_order"),
 sb.from("product_option_groups").select("*").order("sort_order"),sb.from("places").select("*").order("sort_order"),
 sb.from("orders").select("*,diners(display_name),order_items(*)").order("created_at",{ascending:false}).limit(60),
 sb.from("service_calls").select("*").order("created_at",{ascending:false}).limit(60)
]);Object.assign(state,{brands:b.data||[],categories:c.data||[],products:p.data||[],promotions:pr.data||[],groups:g.data||[],options:o.data||[],links:l.data||[],places:pl.data||[],orders:ord.data||[],calls:calls.data||[]})}
$("#loginBtn").onclick=async()=>{const email=$("#authEmail").value.trim(),password=$("#authPassword").value;const {error}=await sb.auth.signInWithPassword({email,password});if(error)return $("#authMessage").textContent=error.message;await enter()}
$("#signupBtn").onclick=async()=>{const email=$("#authEmail").value.trim(),password=$("#authPassword").value;const {error}=await sb.auth.signUp({email,password});$("#authMessage").textContent=error?error.message:"Cuenta creada. Si Supabase solicita confirmación, revisa tu correo y luego inicia sesión."}
$("#logoutBtn").onclick=async()=>{await sb.auth.signOut();showAuth()}
$("#tabs").querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;$("#tabs").querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));render()});
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());

function toolbar(title,eyebrow="ADMINISTRACIÓN",button=""){ $("#sectionTitle").textContent=title;$("#sectionEyebrow").textContent=eyebrow;$("#toolbarActions").innerHTML=button}
function render(){if(state.tab==="products")renderProducts();if(state.tab==="categories")renderCategories();if(state.tab==="promotions")renderPromotions();if(state.tab==="extras")renderExtras();if(state.tab==="branding")renderBranding();if(state.tab==="places")renderPlaces();if(state.tab==="orders")renderOrders()}
function renderProducts(){toolbar("Productos","CATÁLOGO",'<button id="newProduct">+ Nuevo producto</button>');$("#content").innerHTML='<div class="grid">'+state.products.map(p=>`<article class="card"><img src="${p.image_url||""}"><span class="tag">${safe(state.categories.find(c=>c.id===p.category_id)?.name||"Sin categoría")}</span><h3>${safe(p.name)}</h3><p>${safe(p.description||"")}</p><div class="card-footer"><b>L ${Number(p.price).toFixed(2)}</b><button class="edit" data-edit-product="${p.id}">Editar</button></div></article>`).join("")+"</div>";$("#newProduct").onclick=()=>editProduct();$("#content").querySelectorAll("[data-edit-product]").forEach(b=>b.onclick=()=>editProduct(b.dataset.editProduct))}
function productForm(p={}){return `<h2>${p.id?"Editar":"Nuevo"} producto</h2><div class="form-grid">
<label>Nombre<input name="name" value="${safe(p.name||"")}" required></label><label>Precio<input name="price" type="number" step=".01" value="${p.price??0}" required></label>
<label>Marca<select name="brand_id">${state.brands.map(b=>`<option value="${b.id}" ${p.brand_id===b.id?"selected":""}>${safe(b.name)}</option>`).join("")}</select></label>
<label>Categoría<select name="category_id">${state.categories.map(c=>`<option value="${c.id}" ${p.category_id===c.id?"selected":""}>${safe(c.name)}</option>`).join("")}</select></label>
<label class="wide">Descripción<textarea name="description">${safe(p.description||"")}</textarea></label>
<label class="wide">Imagen URL<input name="image_url" value="${safe(p.image_url||"")}"><span class="upload-note">O sube una imagen abajo.</span></label>
<label class="wide">Subir imagen<input name="image_file" type="file" accept="image/jpeg,image/png,image/webp"></label>
<label>Orden<input name="sort_order" type="number" value="${p.sort_order??0}"></label><label>Destacado<select name="featured"><option value="false">No</option><option value="true" ${p.featured?"selected":""}>Sí</option></select></label><label>Activo<select name="active"><option value="true" ${p.active!==false?"selected":""}>Sí</option><option value="false" ${p.active===false?"selected":""}>No</option></select></label>
</div><div class="form-actions">${p.id?'<button type="button" class="danger" id="deleteProduct">Eliminar</button>':""}<button class="primary">Guardar</button></div>`}
async function uploadImage(file,folder){if(!file)return null;const path=`${folder}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error}=await sb.storage.from("menu-media").upload(path,file,{upsert:false});if(error)throw error;return sb.storage.from("menu-media").getPublicUrl(path).data.publicUrl}
async function editProduct(id){const p=id?state.products.find(x=>x.id===id):{};const f=$("#editForm");f.innerHTML=productForm(p);$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);let image=fd.get("image_url");const file=fd.get("image_file");try{if(file?.size)image=await uploadImage(file,"products");const row={id:p.id||("p-"+Date.now()),name:fd.get("name"),price:Number(fd.get("price")),brand_id:fd.get("brand_id"),category_id:fd.get("category_id"),description:fd.get("description"),image_url:image,sort_order:Number(fd.get("sort_order")||0),featured:fd.get("featured")==="true",active:fd.get("active")==="true"};const {error}=await sb.from("products").upsert(row);if(error)throw error;toast("Producto guardado");$("#editDialog").close();await loadAll();render()}catch(err){toast(err.message)}};if(p.id)$("#deleteProduct").onclick=async()=>{if(!confirm("¿Eliminar este producto?"))return;const {error}=await sb.from("products").delete().eq("id",p.id);if(error)return toast(error.message);$("#editDialog").close();await loadAll();render()}}

function renderCategories(){toolbar("Categorías","MENÚ",'<button id="newCategory">+ Nueva categoría</button>');$("#content").innerHTML='<div class="list">'+state.categories.map(c=>`<div class="row"><div><b>${safe(c.name)}</b><small>${safe(state.brands.find(b=>b.id===c.brand_id)?.name||"")} · orden ${c.sort_order}</small></div><div class="row-actions"><button data-edit-cat="${c.id}">Editar</button></div></div>`).join("")+"</div>";$("#newCategory").onclick=()=>editCategory();$("#content").querySelectorAll("[data-edit-cat]").forEach(b=>b.onclick=()=>editCategory(b.dataset.editCat))}
function editCategory(id){const c=id?state.categories.find(x=>x.id===id):{};const f=$("#editForm");f.innerHTML=`<h2>${id?"Editar":"Nueva"} categoría</h2><div class="form-grid"><label>Nombre<input name="name" value="${safe(c.name||"")}" required></label><label>Marca<select name="brand_id">${state.brands.map(b=>`<option value="${b.id}" ${c.brand_id===b.id?"selected":""}>${safe(b.name)}</option>`).join("")}</select></label><label class="wide">Imagen URL<input name="image_url" value="${safe(c.image_url||"")}"></label><label class="wide">Subir imagen<input name="image_file" type="file" accept="image/*"></label><label>Orden<input name="sort_order" type="number" value="${c.sort_order??0}"></label><label>Activo<select name="active"><option value="true">Sí</option><option value="false" ${c.active===false?"selected":""}>No</option></select></label></div><div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);let image=fd.get("image_url");try{const file=fd.get("image_file");if(file?.size)image=await uploadImage(file,"categories");const row={id:c.id||("cat-"+Date.now()),name:fd.get("name"),brand_id:fd.get("brand_id"),image_url:image,sort_order:Number(fd.get("sort_order")||0),active:fd.get("active")==="true"};const {error}=await sb.from("categories").upsert(row);if(error)throw error;$("#editDialog").close();await loadAll();render();toast("Categoría guardada")}catch(err){toast(err.message)}}}
function renderPromotions(){toolbar("Promociones","MARKETING",'<button id="newPromo">+ Nueva promoción</button>');$("#content").innerHTML='<div class="grid">'+state.promotions.map(p=>`<article class="card"><img src="${p.image_url||""}"><h3>${safe(p.title)}</h3><p>${safe(p.subtitle||"")}</p><div class="card-footer"><span class="tag">${p.active?"Activa":"Inactiva"}</span><button class="edit" data-edit-promo="${p.id}">Editar</button></div></article>`).join("")+"</div>";$("#newPromo").onclick=()=>editPromo();$("#content").querySelectorAll("[data-edit-promo]").forEach(b=>b.onclick=()=>editPromo(b.dataset.editPromo))}
function editPromo(id){const p=id?state.promotions.find(x=>x.id===id):{};const f=$("#editForm");f.innerHTML=`<h2>${id?"Editar":"Nueva"} promoción</h2><div class="form-grid"><label>Título<input name="title" value="${safe(p.title||"")}" required></label><label>CTA<input name="cta" value="${safe(p.cta||"Explorar menú")}"></label><label class="wide">Subtítulo<textarea name="subtitle">${safe(p.subtitle||"")}</textarea></label><label>Categoría<select name="category_id"><option value="">Sin categoría</option>${state.categories.map(c=>`<option value="${c.id}" ${p.category_id===c.id?"selected":""}>${safe(c.name)}</option>`).join("")}</select></label><label>Orden<input name="sort_order" type="number" value="${p.sort_order??0}"></label><label class="wide">Imagen URL<input name="image_url" value="${safe(p.image_url||"")}"></label><label class="wide">Subir imagen<input name="image_file" type="file" accept="image/*"></label><label>Activo<select name="active"><option value="true">Sí</option><option value="false" ${p.active===false?"selected":""}>No</option></select></label></div><div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);let image=fd.get("image_url");try{const file=fd.get("image_file");if(file?.size)image=await uploadImage(file,"promotions");const row={title:fd.get("title"),subtitle:fd.get("subtitle"),cta:fd.get("cta"),category_id:fd.get("category_id")||null,image_url:image,sort_order:Number(fd.get("sort_order")||0),active:fd.get("active")==="true"};let q=id?sb.from("promotions").update(row).eq("id",id):sb.from("promotions").insert(row);const {error}=await q;if(error)throw error;$("#editDialog").close();await loadAll();render();toast("Promoción guardada")}catch(err){toast(err.message)}}}

function renderExtras(){toolbar("Extras y opciones","PERSONALIZACIÓN",'<button id="newGroup">+ Nuevo grupo</button>');$("#content").innerHTML='<div class="list">'+state.groups.map(g=>`<div class="row"><div><b>${safe(g.name)}</b><small>${g.selection_type==="multiple"?"Múltiple":"Una opción"} · ${state.options.filter(o=>o.group_id===g.id).length} opciones · ${state.links.filter(l=>l.group_id===g.id).length} productos</small></div><div class="row-actions"><button data-edit-group="${g.id}">Editar</button><button data-add-option="${g.id}">+ Opción</button><button data-link-group="${g.id}">Vincular</button></div></div>`).join("")+"</div>";$("#newGroup").onclick=()=>editGroup();$("#content").querySelectorAll("[data-edit-group]").forEach(b=>b.onclick=()=>editGroup(b.dataset.editGroup));$("#content").querySelectorAll("[data-add-option]").forEach(b=>b.onclick=()=>editOption(b.dataset.addOption));$("#content").querySelectorAll("[data-link-group]").forEach(b=>b.onclick=()=>linkGroup(b.dataset.linkGroup))}
function editGroup(id){const g=id?state.groups.find(x=>x.id===id):{};const f=$("#editForm");f.innerHTML=`<h2>${id?"Editar":"Nuevo"} grupo</h2><div class="form-grid"><label>Nombre<input name="name" value="${safe(g.name||"")}" required></label><label>Selección<select name="selection_type"><option value="single">Una opción</option><option value="multiple" ${g.selection_type==="multiple"?"selected":""}>Varias opciones</option></select></label><label>Tipo de personalización<select name="option_kind"><option value="extra" ${g.option_kind==="extra"?"selected":""}>Extra</option><option value="ingredient" ${g.option_kind==="ingredient"?"selected":""}>Ingrediente</option><option value="removable" ${g.option_kind==="removable"?"selected":""}>Ingrediente removible</option><option value="sauce" ${g.option_kind==="sauce"?"selected":""}>Salsa</option><option value="side" ${g.option_kind==="side"?"selected":""}>Acompañamiento</option><option value="flavor" ${g.option_kind==="flavor"?"selected":""}>Sabor</option><option value="size" ${g.option_kind==="size"?"selected":""}>Tamaño</option><option value="preparation" ${g.option_kind==="preparation"?"selected":""}>Preparación</option><option value="variant" ${!g.option_kind||g.option_kind==="variant"?"selected":""}>Variante</option></select></label><label>Mínimo<input name="min_selections" type="number" value="${g.min_selections??0}"></label><label>Máximo<input name="max_selections" type="number" value="${g.max_selections??1}"></label><label>Orden<input name="sort_order" type="number" value="${g.sort_order??0}"></label></div>${id?'<div class="list" style="margin-top:18px">'+state.options.filter(o=>o.group_id===id).map(o=>`<div class="row"><div><b>${safe(o.name)}</b><small>+${Number(o.price_delta).toFixed(2)}</small></div><button type="button" data-edit-option="${o.id}">Editar</button></div>`).join("")+"</div>":""}<div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.querySelectorAll("[data-edit-option]").forEach(b=>b.onclick=()=>editOption(id,b.dataset.editOption));f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),row={name:fd.get("name"),selection_type:fd.get("selection_type"),option_kind:fd.get("option_kind"),min_selections:Number(fd.get("min_selections")||0),max_selections:Number(fd.get("max_selections")||1),sort_order:Number(fd.get("sort_order")||0),active:true};let q=id?sb.from("option_groups").update(row).eq("id",id):sb.from("option_groups").insert(row);const {error}=await q;if(error)return toast(error.message);$("#editDialog").close();await loadAll();render();toast("Grupo guardado")}}
function editOption(groupId,id){const o=id?state.options.find(x=>x.id===id):{};const f=$("#editForm");f.innerHTML=`<h2>${id?"Editar":"Nueva"} opción</h2><div class="form-grid"><label>Nombre<input name="name" value="${safe(o.name||"")}" required></label><label>Precio extra<input name="price_delta" type="number" step=".01" value="${o.price_delta??0}"></label><label>Orden<input name="sort_order" type="number" value="${o.sort_order??0}"></label></div><div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),row={group_id:groupId,name:fd.get("name"),price_delta:Number(fd.get("price_delta")||0),sort_order:Number(fd.get("sort_order")||0),active:true};let q=id?sb.from("options").update(row).eq("id",id):sb.from("options").insert(row);const {error}=await q;if(error)return toast(error.message);$("#editDialog").close();await loadAll();render();toast("Opción guardada")}}
function linkGroup(groupId){const f=$("#editForm");f.innerHTML=`<h2>Vincular grupo a producto</h2><div class="form-grid"><label class="wide">Producto<select name="product_id">${state.products.map(p=>`<option value="${p.id}">${safe(p.name)}</option>`).join("")}</select></label></div><div class="form-actions"><button class="primary">Vincular</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const {error}=await sb.from("product_option_groups").upsert({product_id:fd.get("product_id"),group_id:groupId,sort_order:0});if(error)return toast(error.message);$("#editDialog").close();await loadAll();render();toast("Grupo vinculado")}}

function renderBranding(){toolbar("Logos y marcas","IDENTIDAD");$("#content").innerHTML='<div class="grid">'+state.brands.map(b=>`<article class="card"><img src="${b.logo_url||""}" style="object-fit:contain;background:#fff"><h3>${safe(b.name)}</h3><p>${safe(b.short_name||"")}</p><div class="card-footer"><span class="tag">${safe(b.accent||"")}</span><button class="edit" data-brand="${b.id}">Editar</button></div></article>`).join("")+"</div>";$("#content").querySelectorAll("[data-brand]").forEach(b=>b.onclick=()=>editBrand(b.dataset.brand))}
function editBrand(id){const b=state.brands.find(x=>x.id===id),f=$("#editForm");f.innerHTML=`<h2>Editar marca</h2><div class="form-grid"><label>Nombre<input name="name" value="${safe(b.name)}"></label><label>Nombre corto<input name="short_name" value="${safe(b.short_name||"")}"></label><label>Color<input name="accent" value="${safe(b.accent||"")}"></label><label class="wide">Logo URL<input name="logo_url" value="${safe(b.logo_url||"")}"></label><label class="wide">Subir logo<input name="image_file" type="file" accept="image/*"></label></div><div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);let logo=fd.get("logo_url");try{const file=fd.get("image_file");if(file?.size)logo=await uploadImage(file,"logos");const {error}=await sb.from("brands").update({name:fd.get("name"),short_name:fd.get("short_name"),accent:fd.get("accent"),logo_url:logo}).eq("id",id);if(error)throw error;$("#editDialog").close();await loadAll();render();toast("Marca actualizada")}catch(err){toast(err.message)}}}
function renderPlaces(){toolbar("Mesas y ubicaciones","OPERACIÓN");$("#content").innerHTML='<div class="list">'+state.places.map(p=>`<div class="row"><div><b>${safe(p.name)}</b><small>${p.code} · ${p.place_type} · ${p.active?"Activa":"Inactiva"}</small></div><div class="row-actions"><button data-place="${p.code}">Editar</button></div></div>`).join("")+"</div>";$("#content").querySelectorAll("[data-place]").forEach(b=>b.onclick=()=>editPlace(b.dataset.place))}
function editPlace(code){const p=state.places.find(x=>x.code===code),f=$("#editForm");f.innerHTML=`<h2>Editar ubicación</h2><div class="form-grid"><label>Nombre<input name="name" value="${safe(p.name)}"></label><label>Tipo<select name="place_type"><option value="TABLE" ${p.place_type==="TABLE"?"selected":""}>Mesa</option><option value="COURT" ${p.place_type==="COURT"?"selected":""}>Cancha</option><option value="DELIVERY" ${p.place_type==="DELIVERY"?"selected":""}>Delivery</option></select></label><label>Tema<select name="theme_key"><option value="PREMIUM" ${p.theme_key==="PREMIUM"?"selected":""}>Premium</option><option value="FOOTBALL" ${p.theme_key==="FOOTBALL"?"selected":""}>Futbolero</option><option value="DELIVERY" ${p.theme_key==="DELIVERY"?"selected":""}>Delivery</option></select></label><label>Orden<input name="sort_order" type="number" value="${p.sort_order||0}"></label><label class="wide">Título de bienvenida<input name="intro_title" value="${safe(p.intro_title||"")}"></label><label class="wide">Subtítulo<input name="intro_subtitle" value="${safe(p.intro_subtitle||"")}"></label><label class="wide">Imagen ambiente URL<input name="hero_image_url" value="${safe(p.hero_image_url||"")}"></label><label>Activo<select name="active"><option value="true">Sí</option><option value="false" ${!p.active?"selected":""}>No</option></select></label></div><div class="form-actions"><button class="primary">Guardar</button></div>`;$("#editDialog").showModal();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const row={name:fd.get("name"),place_type:fd.get("place_type"),theme_key:fd.get("theme_key"),intro_title:fd.get("intro_title"),intro_subtitle:fd.get("intro_subtitle"),hero_image_url:fd.get("hero_image_url"),sort_order:Number(fd.get("sort_order")||0),active:fd.get("active")==="true"};const {error}=await sb.from("places").update(row).eq("code",code);if(error)return toast(error.message);$("#editDialog").close();await loadAll();render();toast("Ubicación actualizada")}}
function renderOrders(){toolbar("Pedidos y servicio","OPERACIÓN");const calls=state.calls.map(c=>`<div class="row"><div><b>🔔 ${safe(c.reason)}</b><small>${new Date(c.created_at).toLocaleString("es-HN")}</small></div><div class="row-actions"><button data-call="${c.id}" data-status="${c.status}">${c.status==="OPEN"?"Marcar atendida":"Atendida"}</button></div></div>`).join("");const orders=state.orders.map(o=>`<div class="row"><div><b>${safe(o.diners?.display_name||"Comensal")} · L ${Number(o.total).toFixed(2)}</b><small>${new Date(o.created_at).toLocaleString("es-HN")} · ${o.order_items?.length||0} productos</small></div><select data-order="${o.id}"><option ${o.status==="RECEIVED"?"selected":""}>RECEIVED</option><option ${o.status==="PREPARING"?"selected":""}>PREPARING</option><option ${o.status==="READY"?"selected":""}>READY</option><option ${o.status==="DELIVERED"?"selected":""}>DELIVERED</option><option ${o.status==="CANCELLED"?"selected":""}>CANCELLED</option></select></div>`).join("");$("#content").innerHTML='<h2>Llamadas de servicio</h2><div class="list">'+calls+'</div><h2 style="margin-top:28px">Pedidos recientes</h2><div class="list">'+orders+"</div>";$("#content").querySelectorAll("[data-order]").forEach(s=>s.onchange=async()=>{const {error}=await sb.from("orders").update({status:s.value}).eq("id",s.dataset.order);if(error)return toast(error.message);toast("Estado actualizado")});$("#content").querySelectorAll("[data-call]").forEach(b=>b.onclick=async()=>{if(b.dataset.status!=="OPEN")return;const {error}=await sb.from("service_calls").update({status:"DONE"}).eq("id",b.dataset.call);if(error)return toast(error.message);await loadAll();render()})}
boot();
