import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const sb=createClient("https://cnynfycmvmcjzaevhvmw.supabase.co","sb_publishable_9Du-_m5etaGt-vCBkDvROw_-0sdB_jT");
const qs=new URLSearchParams(location.search),place=(qs.get("place")||"M01").toUpperCase();
const $=s=>document.querySelector(s), money=n=>"L "+Number(n||0).toLocaleString("es-HN",{minimumFractionDigits:2,maximumFractionDigits:2});
const state={brands:[],categories:[],products:[],promos:[],activeBrand:"LB",activeCategory:null,cart:[],session:null,diner:null,place:null,promoIndex:0};
const safe=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const toast=t=>{const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)};
async function init(){
 const [b,c,p,pr,pl]=await Promise.all([
  sb.from("brands").select("*").eq("active",true).order("sort_order"),
  sb.from("categories").select("*").eq("active",true).order("sort_order"),
  sb.from("products").select("*").eq("active",true).order("sort_order"),
  sb.from("promotions").select("*").eq("active",true).order("sort_order"),
  sb.from("places").select("*").eq("code",place).maybeSingle()
 ]);
 state.brands=b.data||[];state.categories=c.data||[];state.products=p.data||[];state.promos=pr.data||[];state.place=pl.data||{code:place,name:place,place_type:"TABLE"};
 document.body.dataset.placeType=state.place.place_type; $("#placeName").textContent=state.place.name;
 restoreDiner(); renderBrands(); selectBrand("LB"); renderPromos(); renderPromoGrid(); updateCart(); setInterval(nextPromo,4500);
 if(state.diner) await refreshDiners(); else setTimeout(()=>$("#joinDialog").showModal(),700);
}
function restoreDiner(){try{const x=JSON.parse(localStorage.getItem("d504_diner_"+place)||"null");if(x?.session_id&&x?.diner_id){state.diner=x;state.session={id:x.session_id};$("#dinerName").textContent=x.name}}catch{}}
function renderBrands(){const el=$("#brands");el.innerHTML=state.brands.map(b=>`<button class="brand ${b.id===state.activeBrand?"active":""}" data-brand="${b.id}"><img src="${b.logo_url||""}"><span>${safe(b.short_name||b.name)}</span></button>`).join("");el.querySelectorAll("[data-brand]").forEach(x=>x.onclick=()=>selectBrand(x.dataset.brand))}
function selectBrand(id){state.activeBrand=id;renderBrands();const cats=state.categories.filter(c=>c.brand_id===id);state.activeCategory=cats[0]?.id||null;renderCategories();renderProducts()}
function renderCategories(){const cats=state.categories.filter(c=>c.brand_id===state.activeBrand),el=$("#categories");el.innerHTML=cats.map(c=>`<button class="${c.id===state.activeCategory?"active":""}" data-cat="${c.id}"><span>${safe(c.name)}</span></button>`).join("");el.querySelectorAll("[data-cat]").forEach(x=>x.onclick=()=>{state.activeCategory=x.dataset.cat;renderCategories();renderProducts()})}
function renderProducts(){const q=$("#search").value.trim().toLowerCase();const list=state.products.filter(p=>p.brand_id===state.activeBrand&&p.category_id===state.activeCategory&&(!q||(p.name+" "+(p.description||"")).toLowerCase().includes(q)));const el=$("#products");el.innerHTML=list.length?list.map(p=>`<article class="product"><img src="${p.image_url}" alt=""><div class="product-body"><small>${p.brand_id==="LB"?"LA BANDEJA":"BEER STATION"}</small><h3>${safe(p.name)}</h3><p>${safe(p.description||"")}</p><footer><b>${money(p.price)}</b><button data-add="${p.id}">Agregar</button></footer></div></article>`).join(""):`<div class="empty">No hay productos en esta categoría.</div>`;el.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addProduct(b.dataset.add))}
function addProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;const found=state.cart.find(x=>x.product_id===id);if(found)found.qty++;else state.cart.push({product_id:id,qty:1,note:""});updateCart();toast(p.name+" agregado")}
function updateCart(){const count=state.cart.reduce((a,b)=>a+b.qty,0),total=state.cart.reduce((a,i)=>a+(state.products.find(p=>p.id===i.product_id)?.price||0)*i.qty,0);$("#cartCount").textContent=count;$("#cartTotalDock").textContent=money(total);$("#cartDock").classList.toggle("hidden",!count)}
function renderCart(){const el=$("#cartItems");el.innerHTML=state.cart.map((i,n)=>{const p=state.products.find(x=>x.id===i.product_id);return `<div class="cart-line"><div><b>${safe(p?.name)}</b><small>${money(p?.price)} c/u</small></div><div class="qty"><button data-less="${n}">−</button><strong>${i.qty}</strong><button data-more="${n}">+</button></div></div>`}).join("")||'<div class="empty">Tu pedido está vacío.</div>';$("#cartGrand").textContent=money(state.cart.reduce((a,i)=>a+(state.products.find(p=>p.id===i.product_id)?.price||0)*i.qty,0));el.querySelectorAll("[data-more]").forEach(b=>b.onclick=()=>{state.cart[+b.dataset.more].qty++;renderCart();updateCart()});el.querySelectorAll("[data-less]").forEach(b=>b.onclick=()=>{const i=+b.dataset.less;if(--state.cart[i].qty<=0)state.cart.splice(i,1);renderCart();updateCart()})}
async function joinTable(){const name=$("#joinName").value.trim();if(!name)return toast("Escribe tu nombre");const {data,error}=await sb.rpc("join_table_public",{p_place:place,p_name:name});if(error)return toast(error.message);state.diner={...data,name};state.session={id:data.session_id};localStorage.setItem("d504_diner_"+place,JSON.stringify(state.diner));$("#dinerName").textContent=name;$("#joinDialog").close();await refreshDiners();toast("Te uniste a "+state.place.name)}
async function refreshDiners(){if(!state.session?.id)return;const {data}=await sb.rpc("get_table_diners_public",{p_session:state.session.id});const list=Array.isArray(data)?data:[];$("#diners").innerHTML=list.map(d=>`<span class="diner">${safe(d.name).slice(0,1).toUpperCase()}</span>`).join("");$("#dinerCount").textContent=list.length+" comensal"+(list.length===1?"":"es")}
async function sendOrder(){if(!state.diner){$("#joinDialog").showModal();return}if(!state.cart.length)return toast("Agrega productos");const payload={session_id:state.session.id,diner_id:state.diner.diner_id,items:state.cart};const btn=$("#sendOrder");btn.disabled=true;btn.textContent="Enviando…";const {data,error}=await sb.rpc("place_order_public",{p_payload:payload});btn.disabled=false;btn.textContent="Enviar pedido";if(error)return toast(error.message);const saved=JSON.parse(localStorage.getItem("d504_orders")||"[]");saved.unshift({token:data.tracking_token,total:data.total,created_at:new Date().toISOString()});localStorage.setItem("d504_orders",JSON.stringify(saved.slice(0,12)));state.cart=[];updateCart();$("#cartDialog").close();toast("Pedido enviado ✅")}
async function callStaff(reason){if(!state.diner){$("#joinDialog").showModal();return}const {error}=await sb.rpc("call_staff_public",{p_payload:{session_id:state.session.id,diner_id:state.diner.diner_id,reason}});toast(error?error.message:"Solicitud enviada")}
function renderPromos(){if(!state.promos.length)return;const p=state.promos[state.promoIndex%state.promos.length];$("#promoHero").innerHTML=`<img src="${p.image_url}"><div class="promo-copy"><small>DESTACADO</small><h2>${safe(p.title)}</h2><p>${safe(p.subtitle||"")}</p><button data-promo-brand="${p.brand_id||"LB"}">${safe(p.cta||"Explorar")}</button></div>`;$("#promoHero button").onclick=()=>selectBrand($("#promoHero button").dataset.promoBrand);$("#promoDots").innerHTML=state.promos.map((_,i)=>`<button class="${i===state.promoIndex?"active":""}" data-dot="${i}"></button>`).join("");$("#promoDots").querySelectorAll("[data-dot]").forEach(d=>d.onclick=()=>{state.promoIndex=+d.dataset.dot;renderPromos()})}
function nextPromo(){if(!state.promos.length)return;state.promoIndex=(state.promoIndex+1)%state.promos.length;renderPromos()}
function renderPromoGrid(){const el=$("#promoGrid");el.innerHTML=state.promos.slice(0,4).map(p=>`<article><img src="${p.image_url}"><div><b>${safe(p.title)}</b><span>${safe(p.subtitle||"")}</span></div></article>`).join("")}
$("#search").oninput=renderProducts;$("#cartDock").onclick=()=>{renderCart();$("#cartDialog").showModal()};$("#cartTop").onclick=()=>{renderCart();$("#cartDialog").showModal()};$("#joinButton").onclick=joinTable;$("#sendOrder").onclick=sendOrder;$("#bellButton").onclick=()=>$("#serviceDialog").showModal();document.querySelectorAll("[data-service]").forEach(b=>b.onclick=()=>{callStaff(b.dataset.service);$("#serviceDialog").close()});document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());init();
